module boolean_gr # (parameter C_BOOLEAN_GENERATOR_NUM = 24) (
    input clk,                          // clock to shift init value in
    input [C_BOOLEAN_GENERATOR_NUM-1:0] boolean_data_i,    	// 24 header pins input
    input start,                        // start reconfigure CFGLUT
    input [31:0] fn_init_value,         // reconfigure CFGLUT value
    input [24:0] boolean_input_sel,      // 5 bits per input pin, 5 input 
    output boolean_data_o            	// output result
    );
    
    wire ce;
    wire CLR;
    wire [4:0] boolean_i;
     
    // Convert longer then 1 clocks pulse generated by GPIO write to one clock pulse
    FDCE #(
           .INIT(1'b0) // Initial value of register (1'b0 or 1'b1)
        ) FDCE_inst (
           .Q(Q1),      // 1-bit Data output
           .C(start),      // 1-bit Clock input
           .CE(1'b1),    // 1-bit Clock enable input
           .CLR(CLR),  // 1-bit Asynchronous clear input
           .D(1'b1)       // 1-bit Data input
        );

    FDCE #(
           .INIT(1'b0) // Initial value of register (1'b0 or 1'b1)
        ) FDCE_inst_1 (
           .Q(CLR),      // 1-bit Data output
           .C(clk),      // 1-bit Clock input
           .CE(1'b1),    // 1-bit Clock enable input
           .CLR(1'b0),  // 1-bit Asynchronous clear input
           .D(Q1)       // 1-bit Data input
        );

    boolean_fsm fsm(.clk(clk), .start(CLR), .fn_init_value(fn_init_value), .cdi(cdi), .ce(ce), .done(done));
    
    boolean_input # (C_BOOLEAN_GENERATOR_NUM) input_sel (.sel(boolean_input_sel), .datapin(boolean_data_i), .boolean_o(boolean_i));
    
    boolean_lut boolean_bit0 (.clk(clk), .ce(ce), .data_in(boolean_i), .CDI(cdi), .result(boolean_data_o));
    
endmodule

// Finite State Machine
module boolean_fsm(
    input clk,           // clock
    input start,         // start reconfigure CFGLUT
    input [31:0] fn_init_value, // reconfigure CFGLUT value
    output reg [4:0] cdi, // output CDI signal
    output reg ce,        // output CE signal
    output reg done       // output done signal
    );
    
    localparam [1:0]
        IDLE = 2'b00,
        RECONFIG = 2'b01,
        WAIT = 2'b10;
        
    reg [1:0] state, next_state;
    
    always @(posedge clk) begin
        state <= next_state;
    end
    
    always @(*) begin
        next_state = state;
        ce = 0;
        cdi = 0;
        done = 0;
        
        case (state)
            IDLE: begin
                if (start) begin
                    next_state = RECONFIG;
                end
            end
            
            RECONFIG: begin
                ce = 1;
                cdi = fn_init_value[4:0];
                next_state = WAIT;
            end
            
            WAIT: begin
                ce = 1;
                done = 1;
            end
        endcase
    end
endmodule

// Input Selection
module boolean_input # (parameter C_BOOLEAN_GENERATOR_NUM = 24) (
    input [24:0] sel,
    input [C_BOOLEAN_GENERATOR_NUM-1:0] datapin,
    output [4:0] boolean_o
    );
    
    assign boolean_o = {datapin[sel[4:0]*5 +: 5], datapin[sel[9:5]*5 +: 5], datapin[sel[14:10]*5 +: 5], datapin[sel[19:15]*5 +: 5], datapin[sel[24:20]*5 +: 5]};
    
endmodule

// LUT
module boolean_lut(
    input clk,           // clock
    input ce,            // clock enable
    input [4:0] data_in, // input data
    input [4:0] CDI,     // configuration data input
    output reg result    // output result
    );
    
    reg [31:0] lut;
    
    always @(posedge clk) begin
        if (ce) begin
            lut <= CDI;
        end
    end
    
    always @(*) begin
        result = lut[data_in];
    end
endmodule

// D Flip-Flop with Clear and Enable
module FDCE (
    output reg Q,    // 1-bit Data output
    input C,         // 1-bit Clock input
    input CE,        // 1-bit Clock enable input
    input CLR,       // 1-bit Asynchronous clear input
    input D          // 1-bit Data input
    );
    
    always @(posedge C) begin
        if (CLR) begin
            Q <= 1'b0;
        end else if (CE) begin
            Q <= D;
        end
    end
endmodule